### ISSUE TITLE
[Bug]: find_by_id with imdb id doesn't show all results

### ISSUE THREAD

**Issue by andy71** [meisnate12/TMDbAPIs#1]
### Version Number

1.0.3

### Describe the Bug

The IMDb ID can be assigned in multiple entries in TMDb. For example the IMDb ID tt0463850 (10.5 Apocalypse).

When using the API via browser I get both results, the movie result and the tv result. But using TMDbAPIs I got only the first result, the movie result.

I am not sure if this is a bug. But from my side of view, I would expect to get a list of all results.

**Comment by meisnate12** [comment]
how are you using the object because im able to get both the movie and tv results although i will say in general the imdb ids are supposed to only be attached to a single item on TMDb the "movie" entry for that series should be deleted
```python
from tmdbapis import TMDbAPIs

apikey = "YOURKEY"

tmdb = TMDbAPIs(apikey)
results = tmdb.find_by_id(imdb_id="tt0463850")
print(results.movie_results)
print(results.tv_results)
```

**Comment by andy71** [comment]
I am so sorry. That was my fault. I saw the .movie_results, but did not realized there could be a .tv_results.
Thank you.

**Comment by meisnate12** [comment]
Side Note the movie has been removed
